name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y meson libcjson-dev valgrind
    - name: Test
      run: |
        meson setup builddir
        cd builddir
        meson test --wrapper="valgrind --leak-check=full --track-origins=yes --error-exitcode=125" --print-errorlogs
